/**
 * Export the GenOS 33-component contract as JSON Schema (plan §3.3, Layer 0).
 *
 * Loads the REAL contract (src/genos/ui/contract.tsx) through the fixture
 * generator's toolchain (esbuild TS stripping + @openuidev/lang-core), builds
 * the library with stub renderers, and writes zod's JSON-schema conversion
 * (`library.toJSONSchema()`, i.e. z.toJSONSchema over every component's props
 * schema, with cross-component refs hoisted into $defs) to
 * spec/contract/genos.schema.json — deterministically (sorted keys).
 *
 * This is the exact schema document the parser consumes: lang-core's
 * createStreamingParser derives its positional-arg -> named-prop ParamMap
 * from $defs[<Component>].properties (key order) and .required.
 *
 * Run from the repo root:   node spec/contract/export-schema.mjs
 * Requires the generator's deps:  cd spec/fixtures/generator && npm install
 */
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const generatorDir = path.resolve(here, "../fixtures/generator");

if (!existsSync(path.join(generatorDir, "node_modules"))) {
  console.error(
    "[export-schema] generator dependencies missing.\n" +
      "  Run: (cd spec/fixtures/generator && npm install) first.",
  );
  process.exit(1);
}

const { buildLibrary, CONTRACT_PATH } = await import(
  pathToFileURL(path.join(generatorDir, "lib/build-library.mjs")).href
);

/** Recursively sort object keys for a stable, diffable output. */
function sortKeysDeep(v) {
  if (Array.isArray(v)) return v.map(sortKeysDeep);
  if (v && typeof v === "object") {
    const out = {};
    for (const k of Object.keys(v).sort()) out[k] = sortKeysDeep(v[k]);
    return out;
  }
  return v;
}

const library = await buildLibrary();
const componentNames = Object.keys(library.components).sort();
const doc = {
  $comment:
    "GENERATED by spec/contract/export-schema.mjs from src/genos/ui/contract.tsx " +
    "via @openuidev/lang-core library.toJSONSchema() (zod z.toJSONSchema). Do not edit by hand. " +
    "The parser derives positional-arg order from each $defs entry's `properties` key order " +
    "and requiredness from `required` — but note THIS file sorts keys alphabetically for " +
    "diff stability, so positional order is captured separately in `paramOrder`.",
  root: library.root,
  componentCount: componentNames.length,
  components: componentNames,
  // Positional order is semantic (Zod key order = positional arg order) and
  // would be destroyed by key sorting, so it is captured explicitly:
  paramOrder: Object.fromEntries(
    componentNames.map((name) => {
      const schema = library.toJSONSchema();
      const def = schema.$defs?.[name] ?? {};
      const required = def.required ?? [];
      return [
        name,
        Object.keys(def.properties ?? {}).map((p) => ({
          name: p,
          required: required.includes(p),
        })),
      ];
    }),
  ),
  schema: sortKeysDeep(library.toJSONSchema()),
};

const outPath = path.join(here, "genos.schema.json");
writeFileSync(outPath, JSON.stringify(doc, null, 2) + "\n");
console.log(
  `[export-schema] wrote ${path.relative(process.cwd(), outPath)} ` +
    `(${componentNames.length} components from ${path.relative(process.cwd(), CONTRACT_PATH)})`,
);
