import Foundation
import OpenUILang
import Testing

/// Deterministic multi-`set(_:)` streaming scenarios (spec/openui-lang.md §10)
/// that the single-shot fixture corpus cannot express: prefix-extension
/// caching, completed-duplicate overwrite vs pending-cannot-overwrite,
/// non-prefix reset, and the apostrophe-comment glue hazard.
///
/// EXPECTED TREES: every inline JSON string below was generated by running the
/// exact same `set(_:)` sequence through the JS reference implementation
/// (@openuidev/lang-core `createStreamingParser` + the fixture generator's
/// serialization pipeline in `spec/fixtures/generator/lib/`), i.e. a
/// throwaway script that called `sp.set(step)` per step and printed
/// `stableStringify(serializeExpected(...))` for each result. They are
/// byte-exact oracle outputs, not hand-written approximations.
@Suite struct StreamingSemanticsTests {
    static let schema: LibrarySchema = {
        // Same contract the fixture oracle uses.
        try! LibrarySchema.load(from: FixtureCorpus.schemaURL)
    }()

    /// Runs the steps through ONE streaming parser and asserts each step's
    /// serialization byte-matches the JS oracle's output for the same call
    /// sequence.
    private func runScenario(_ name: String, steps: [(text: String, expected: String)]) {
        let parser = StreamingParser(schema: Self.schema)
        for (i, step) in steps.enumerated() {
            let result = parser.set(step.text)
            let actual = TreeSerializer.serialize(result)
            #expect(
                actual == step.expected,
                "\(name) step \(i): serialized tree diverged from JS oracle"
            )
        }
    }

    /// set(p1) then set(p1+p2): the completed `root` statement is served from
    /// the prefix-extension cache while the appended pending `$n = 5` joins
    /// the parse — the auto-declared `$n: null` upgrades to 5.
    @Test func prefixExtensionCaching() {
        runScenario(
            "prefixExtension",
            steps: [
                (
                    "root = Card([CardHeader(\"Count: \" + $n)])\n",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "props": {
                              "title": "Count: "
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": false,
                        "unresolved": [],
                        "errors": []
                      },
                      "state": {
                        "$n": null
                      },
                      "runtimeErrors": []
                    }

                    """
                ),
                (
                    "root = Card([CardHeader(\"Count: \" + $n)])\n$n = 5",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "props": {
                              "title": "Count: 5"
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": false,
                        "unresolved": [],
                        "errors": []
                      },
                      "state": {
                        "$n": 5
                      },
                      "runtimeErrors": []
                    }

                    """
                ),
            ]
        )
    }

    /// Batch (single set): two COMPLETED statements with the same id — the
    /// later one overwrites (`Map.set` semantics), keeping insertion position.
    @Test func batchCompletedDuplicateOverwrites() {
        runScenario(
            "batchDuplicateOverwrite",
            steps: [
                (
                    "root = Card([TextContent(\"one\")])\nroot = Card([TextContent(\"two\")])\n",
                    Self.rootWithText("two", incomplete: false)
                )
            ]
        )
    }

    /// Streaming: a PENDING statement (no trailing newline) with an id already
    /// in the completed cache is DISCARDED — pending can never overwrite
    /// completed.
    @Test func pendingCannotOverwriteCompleted() {
        runScenario(
            "pendingCannotOverwriteCompleted",
            steps: [
                (
                    "root = Card([TextContent(\"one\")])\n",
                    Self.rootWithText("one", incomplete: false)
                ),
                (
                    // Redefinition is still pending (no trailing newline):
                    // "one" must survive.
                    "root = Card([TextContent(\"one\")])\nroot = Card([TextContent(\"two\")])",
                    Self.rootWithText("one", incomplete: false)
                ),
            ]
        )
    }

    /// Streaming: once the duplicate is newline-terminated it COMPLETES and
    /// overwrites its predecessor (contrast with the pending case above).
    @Test func streamedCompletedDuplicateOverwrites() {
        runScenario(
            "streamedDuplicateOverwrite",
            steps: [
                (
                    "root = Card([TextContent(\"one\")])\n",
                    Self.rootWithText("one", incomplete: false)
                ),
                (
                    "root = Card([TextContent(\"one\")])\nroot = Card([TextContent(\"two\")])\n",
                    Self.rootWithText("two", incomplete: false)
                ),
            ]
        )
    }

    /// set() with text that is NOT a prefix-extension of the previous text
    /// resets the parser: the old completed cache is discarded entirely.
    @Test func nonPrefixResets() {
        runScenario(
            "nonPrefixReset",
            steps: [
                (
                    "root = Card([TextContent(\"one\")])\n",
                    Self.rootWithText("one", incomplete: false)
                ),
                (
                    "root = Card([TextContent(\"reset\")])\n",
                    Self.rootWithText("reset", incomplete: false)
                ),
            ]
        )
    }

    /// Apostrophe-comment glue hazard: the statement scanner is comment-BLIND
    /// and quote-aware, so the `'` in `# don't split here` opens a bogus
    /// string context and every later newline is glued into one pending blob
    /// (the completed watermark never advances past the comment). The pending
    /// blob is comment-stripped and re-parsed on EVERY set, so statements
    /// after the comment still resolve — across multiple sets — and a
    /// genuinely unclosed string at the tail flags `meta.incomplete`.
    @Test func apostropheCommentGlue() {
        runScenario(
            "apostropheCommentGlue",
            steps: [
                (
                    "root = Card([header, tail])\n# don't split here\nheader = CardHeader(\"Streams\")\n",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "statementId": "header",
                            "props": {
                              "title": "Streams"
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": false,
                        "unresolved": [
                          "tail"
                        ],
                        "errors": []
                      },
                      "state": {},
                      "runtimeErrors": []
                    }

                    """
                ),
                (
                    "root = Card([header, tail])\n# don't split here\nheader = CardHeader(\"Streams\")\n"
                        + "tail = TextContent(\"done: \" + $ok)\n$ok = \"yes",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "statementId": "header",
                            "props": {
                              "title": "Streams"
                            }
                          },
                          {
                            "component": "TextContent",
                            "statementId": "tail",
                            "props": {
                              "text": "done: yes"
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": true,
                        "unresolved": [],
                        "errors": []
                      },
                      "state": {
                        "$ok": "yes"
                      },
                      "runtimeErrors": []
                    }

                    """
                ),
            ]
        )
    }

    /// Chunk boundary INSIDE a CRLF pair: the first set() ends with the "\r"
    /// of a "\r\n" (the "\n" and the next statements arrive in the second
    /// set()). With code-unit scanning this is chunk-boundary-independent:
    /// the "\r" is horizontal whitespace, the later "\n" splits statements
    /// exactly as if the full text had arrived in one set(). (Grapheme-cluster
    /// scanning merged "\r\n" into ONE Character and never split.)
    ///
    /// EXPECTED TREES derived from the JS oracle like every scenario above: a
    /// throwaway script ran this exact set() sequence through ONE
    /// `createStreamingParser` (lang-core) and printed
    /// `stableStringify(serializeExpected(result, evaluatedRoot, errors))`
    /// per step, with the store/evaluateElementProps pipeline copied from
    /// `spec/fixtures/generator/generate.mjs`. Step 0: `hd` completes at the
    /// mid-buffer "\r\n"; the trailing "\r" leaves no pending statement, so
    /// `incomplete` is false and only `tl` is unresolved. Step 1: the
    /// appended "\n" completes the CRLF, and `tl` / `$z` parse normally.
    @Test func chunkBoundaryInsideCRLF() {
        runScenario(
            "chunkBoundaryInsideCRLF",
            steps: [
                (
                    "root = Card([hd, tl])\r\nhd = CardHeader(\"Split\")\r",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "statementId": "hd",
                            "props": {
                              "title": "Split"
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": false,
                        "unresolved": [
                          "tl"
                        ],
                        "errors": []
                      },
                      "state": {},
                      "runtimeErrors": []
                    }

                    """
                ),
                (
                    "root = Card([hd, tl])\r\nhd = CardHeader(\"Split\")\r"
                        + "\ntl = TextContent(\"tail: \" + $z)\r\n$z = 9\r\n",
                    """
                    {
                      "root": {
                        "component": "Card",
                        "statementId": "root",
                        "props": {},
                        "children": [
                          {
                            "component": "CardHeader",
                            "statementId": "hd",
                            "props": {
                              "title": "Split"
                            }
                          },
                          {
                            "component": "TextContent",
                            "statementId": "tl",
                            "props": {
                              "text": "tail: 9"
                            }
                          }
                        ]
                      },
                      "meta": {
                        "incomplete": false,
                        "unresolved": [],
                        "errors": []
                      },
                      "state": {
                        "$z": 9
                      },
                      "runtimeErrors": []
                    }

                    """
                ),
            ]
        )
    }

    /// Shared oracle output for the single-TextContent scenarios above
    /// (identical modulo the text), byte-for-byte as printed by the JS
    /// pipeline.
    private static func rootWithText(_ text: String, incomplete: Bool) -> String {
        """
        {
          "root": {
            "component": "Card",
            "statementId": "root",
            "props": {},
            "children": [
              {
                "component": "TextContent",
                "props": {
                  "text": "\(text)"
                }
              }
            ]
          },
          "meta": {
            "incomplete": \(incomplete ? "true" : "false"),
            "unresolved": [],
            "errors": []
          },
          "state": {},
          "runtimeErrors": []
        }

        """
    }
}

/// Schema `default` application (materialize.js: a missing/null REQUIRED prop
/// takes `p.defaultValue` before missing-required/null-required is reported).
/// The shipped GenOS contract declares no defaults, so this is exercised with
/// a hand-built schema.
@Suite struct SchemaDefaultValueTests {
    private static func makeSchema() -> LibrarySchema {
        LibrarySchema(
            root: "Card",
            components: ["Card", "Badge"],
            paramOrder: [
                "Card": [.init(name: "children", required: true)],
                "Badge": [
                    .init(name: "label", required: true, defaultValue: .string("fallback")),
                    .init(name: "count", required: true),
                ],
            ],
            schema: .object([:])
        )
    }

    @Test func defaultFillsNullRequiredProp() {
        let result = OpenUIParser(schema: Self.makeSchema())
            .parse("root = Card([Badge(null, 3)])\n")
        #expect(result.meta.errors.isEmpty)
        guard case .array(let children)? = result.root?.children,
            case .element(let badge)? = children.first
        else {
            Issue.record("expected Badge element child")
            return
        }
        #expect(badge.component == "Badge")
        #expect(badge.props["label"] == .string("fallback"))
        #expect(badge.props["count"] == .number(3))
    }

    @Test func missingPropWithoutDefaultStillErrors() {
        let result = OpenUIParser(schema: Self.makeSchema())
            .parse("root = Card([Badge(null)])\n")
        // label's default is applied, but count has none: exactly one
        // missing-required error and the element is dropped.
        #expect(result.meta.errors.count == 1)
        #expect(result.meta.errors.first?.code == .missingRequired)
        #expect(result.meta.errors.first?.path == "/count")
        if case .array(let children)? = result.root?.children {
            #expect(children.isEmpty)
        }
    }

    /// The real contract file currently carries no `default` for any property;
    /// loading it must therefore yield nil defaultValues everywhere.
    @Test func shippedContractHasNoDefaults() throws {
        let schema = try LibrarySchema.load(from: FixtureCorpus.schemaURL)
        let withDefaults = schema.paramOrder.values
            .flatMap { $0 }
            .filter { $0.defaultValue != nil }
        #expect(withDefaults.isEmpty)
    }
}
